name: Use Secrets and Environments

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Environment Secret
        run: echo "The API key is $API_KEY"
        env:
          API_KEY: ${{ secrets.API_KEY }} 
