name: Simple CI on Push

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  

      - name: Display success message
        run: echo "CI workflow completed successfully!"
